title: "DnD Mini Wiki"
baseurl: ""
url: ""
# remote_theme: pages-themes/minimal@v0.2.0
plugins:
# - jekyll-remote-theme
  - jekyll-seo-tag
markdown: kramdown
collections:
  content:
    output: true
defaults:
  - scope:
      path: "content"
    values:
      layout: "default"
